# Generated by Django 4.1.5 on 2023-01-29 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='img',
            new_name='image',
        ),
    ]
